# Generated by Django 4.1.7 on 2023-03-30 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='startupBasicInfo',
        ),
    ]
