# Generated by Django 4.1.7 on 2023-03-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startup', '0002_delete_startupbasicinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='startupBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('investment', models.IntegerField()),
                ('roi', models.IntegerField()),
                ('Repayments', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
