# Generated by Django 4.1.7 on 2023-03-31 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
        ('startup', '0004_startupbasicinfo_bin_startupbasicinfo_licence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupbasicinfo',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auths.auts'),
        ),
    ]
