# Generated by Django 4.1.7 on 2023-04-25 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
        ('startup', '0005_startupbasicinfo_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='startupBasicInfo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('companyAddress', models.CharField(max_length=100)),
                ('companyDescription', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auths.auts')),
            ],
        ),
    ]
