# Generated by Django 4.1.7 on 2023-04-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0006_startupbasicinfo2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='startupBasicInfo2',
        ),
    ]
