# Generated by Django 4.1.7 on 2023-04-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
        ('backupStartupDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyForFundrising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('investment', models.IntegerField()),
                ('roi', models.IntegerField()),
                ('Repayments', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='', upload_to='')),
                ('vat', models.ImageField(default='', upload_to='')),
                ('bin', models.ImageField(default='', upload_to='')),
                ('licence', models.ImageField(default='', upload_to='')),
                ('revenue', models.IntegerField()),
                ('gross_margin', models.IntegerField()),
                ('mrr', models.IntegerField()),
                ('cac', models.IntegerField()),
                ('burn_rate', models.IntegerField()),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auths.auts')),
            ],
        ),
    ]
