# Generated by Django 4.1.7 on 2023-04-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
        ('backupStartupDB', '0002_applyforfundrising'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforfundrising',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='monthlyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateTimeField()),
                ('currentRevenue', models.IntegerField()),
                ('currentProfit', models.IntegerField()),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auths.auts')),
            ],
        ),
    ]
