# Generated by Django 4.1.7 on 2023-04-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backupStartupDB', '0003_applyforfundrising_status_monthlyrevenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyforfundrising',
            name='status',
        ),
    ]
