# Generated by Django 4.1.7 on 2023-04-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backupStartupDB', '0004_remove_applyforfundrising_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforfundrising',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
