# Generated by Django 4.1.7 on 2023-04-28 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backupStartupDB', '0006_return_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_profit',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
