# Generated by Django 4.1.7 on 2023-04-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
        ('backupStartupDB', '0007_alter_return_profit_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='return_profit',
            new_name='profit',
        ),
    ]
