# Generated by Django 4.1.6 on 2023-03-31 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_invest_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invest',
            name='month',
        ),
    ]
