# Generated by Django 4.1.6 on 2023-03-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0003_remove_invest_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='mm',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invest',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
