# Generated by Django 4.1.6 on 2023-03-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0004_invest_mm_alter_invest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest',
            name='mm',
            field=models.CharField(max_length=4),
        ),
    ]
