# Generated by Django 4.1.6 on 2023-03-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0005_alter_invest_mm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invest',
            name='mm',
        ),
    ]
