# Generated by Django 4.1.6 on 2023-03-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0006_remove_invest_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='mnth',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
