# Generated by Django 4.1.6 on 2023-03-31 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0007_invest_mnth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invest',
            name='mnth',
        ),
    ]
