# Generated by Django 4.1.6 on 2023-03-31 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0008_remove_invest_mnth'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='mnth',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
