# Generated by Django 4.1.6 on 2023-03-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0009_invest_mnth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest',
            name='mnth',
            field=models.CharField(default='01', max_length=20),
        ),
    ]
