# Generated by Django 4.1.7 on 2023-03-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0011_remove_invest_mnth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest',
            name='date',
            field=models.DateField(),
        ),
    ]
