# Generated by Django 4.1.6 on 2023-03-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=35)),
                ('catagory', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=35)),
            ],
        ),
    ]
