# Generated by Django 4.1.7 on 2023-04-26 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_image_alter_blogs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 17, 31, 54, 804936)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
