# Generated by Django 4.1.7 on 2023-04-22 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(default=datetime.datetime(2023, 4, 22, 20, 42, 14, 194569))),
                ('post_title', models.CharField(max_length=50)),
                ('post_des', models.CharField(max_length=1000)),
                ('post_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_by', to='auths.auts')),
            ],
        ),
    ]
