# Generated by Django 4.1.7 on 2023-04-22 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_communitypost_post_date_communitycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycomment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 22, 23, 20, 57, 560145)),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 22, 23, 20, 57, 560145)),
        ),
    ]
