# Generated by Django 4.1.7 on 2023-04-22 18:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
        ('community', '0003_communitycomment_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycomment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 0, 47, 4, 472046)),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 0, 47, 4, 471045)),
        ),
        migrations.CreateModel(
            name='CommentNofity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('notify', models.CharField(max_length=30)),
                ('status', models.IntegerField(default=0)),
                ('comment_date', models.DateTimeField(default=datetime.datetime(2023, 4, 23, 0, 47, 4, 472046))),
                ('comment_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nf_comment_by', to='auths.auts')),
                ('post_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nf_post_by', to='auths.auts')),
            ],
        ),
    ]
