# Generated by Django 5.0.4 on 2024-05-06 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_alter_commentnofity_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentnofity',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 20, 26, 57, 912623)),
        ),
        migrations.AlterField(
            model_name='communitycomment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 20, 26, 57, 912623)),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 20, 26, 57, 911622)),
        ),
    ]
