# Generated by Django 4.1.7 on 2023-04-22 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_messagedb_status_alter_messagedb_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedb',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 22, 20, 42, 14, 68073)),
        ),
    ]
