# Generated by Django 4.1.7 on 2023-04-28 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
        ('chatapp', '0007_alter_messagedb_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedb',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 14, 53, 45, 273534)),
        ),
        migrations.CreateModel(
            name='MessageNofity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.CharField(max_length=30)),
                ('status', models.IntegerField(default=0)),
                ('comment_date', models.DateTimeField(default=datetime.datetime(2023, 4, 28, 14, 53, 45, 273534))),
                ('msg_send_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_send_by', to='auths.auts')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='auths.auts')),
            ],
        ),
    ]
