# Generated by Django 4.1.7 on 2023-04-28 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0008_alter_messagedb_send_date_messagenofity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedb',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 16, 1, 5, 989516)),
        ),
        migrations.AlterField(
            model_name='messagenofity',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 16, 1, 5, 989516)),
        ),
        migrations.AlterField(
            model_name='messagenofity',
            name='msg_send_by',
            field=models.IntegerField(),
        ),
    ]
