# Generated by Django 5.0.4 on 2024-04-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0013_alter_messagedb_send_date_and_more'),
        ('chatapp', '0016_alter_messagedb_send_date'),
    ]

    operations = [
    ]
