# Generated by Django 5.0.4 on 2024-05-06 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0018_alter_messagedb_send_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedb',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 20, 26, 57, 910622)),
        ),
        migrations.AlterField(
            model_name='messagenofity',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 20, 26, 57, 911622)),
        ),
    ]
